name: on_push

# When the event should run
on:
  push:
    branches:
      - "**" # This will run on all branches, and must be quoted to be handled by yaml
  #schedule:
    #- cron: '*/10 * * * *'

# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: build-pipeline
          job-status: ${{ job.status }}

      - name: Checkout code
        uses: actions/checkout@v2

      # Install java
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', 'oraclejdk'
          java-version: '21'


      # Add another detailed directory listing for more insights
      - name: List All Directories
        run: |
          echo "All directories:"
          find . -type d

      # Ensure the script is executable
      - name: Make test_result_script.sh executable
        run: chmod +x ./resources/test_result_script.sh

      # List the file permissions to ensure the script is executable
      - name: List file permissions of test_result_script.sh
        run: ls -l ./resources/test_result_script.sh

      # Run Maven tests
      - name: Run tests with maven
        run: mvn test

      # Collect build data
      - name: Collect build data
        env:
          PUSHGATEWAY_URL: ${{ secrets.PUSHGATEWAY_URL }}
        if: always()
        run: |
          echo "github_actions_total_duration $(expr $(date +%s) - ${START_TIME})" | curl --data-binary @- ${PUSHGATEWAY_URL}/metrics/job/github_actions
          ./resources/test_result_script.sh
